import time
print("========================================================")
print("Olá vamos fazer um jogo")
print("========================================================")
time.sleep(2)
print("Pense em um numero!")
time.sleep(2)
num = int(input("Pensou? Agora digite o numero que você pensou:" '\n'))
time.sleep(3)
print("Agora some com mais 5!")
time.sleep(4)
print("Agora multiplique por 2!")
time.sleep(4)
print("Agora subtraia por 4!")
time.sleep(4)
print("Agora divide por 2!")
time.sleep(4)
print("Agora subtraia pelo numero que você pensou!")
time.sleep(4)
res = int(((num + 5) * 2 - 4) / 2 - num)
time.sleep(4)
print("Acertei!!! o resultado é:" , res)